#!/usr/bin/env node
/**
 * Generate tokens/colors.css, tokens/colors.json and tokens/tailwind.css from
 * the DTCG token JSON.
 *
 *   node scripts/build-tokens.mjs          write the files
 *   node scripts/build-tokens.mjs --check  verify they are current, write nothing
 *
 * Source of truth is tokens/primitive.json + tokens/semantic.{dark,light}.json,
 * in the DTCG Design Tokens Format Module 2025.10. The CSS and colors.json are
 * OUTPUT — never edit them.
 *
 * This exists because three hand-maintained files describing one palette is how
 * they drift, and they had already drifted: colors.json carried no light-mode
 * brand values at all while colors.css did, so a consumer reading the JSON got
 * dark values in both themes with nothing to warn it.
 *
 * `--check` is the gate you run in review rather than a convention people
 * remember. It writes nothing and exits non-zero when the output is stale.
 *
 * Node only, no dependencies. A committed command you run by hand, not a build
 * step anything installs.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const T = (n) => JSON.parse(readFileSync(join(root, 'tokens', n), 'utf8'));

const prim = T('primitive.json');
const dark = T('semantic.dark.json');
const light = T('semantic.light.json');

// ── value rendering ─────────────────────────────────────────────────────────

const c255 = (n) => Math.round(n * 255);
/** A family name containing a space must be quoted in CSS. */
const family = (n) => (/\s/.test(n) ? `'${n}'` : n);
const px = (d) => (d.value === 0 ? '0' : `${d.value}${d.unit}`);

/** A semantic alias `{color.green-neon}` becomes a var() at the palette prefix. */
const aliasVar = (path) => `var(--ol-${path.split('.').slice(1).join('-')})`;

function val(v) {
  if (typeof v === 'string' && v.startsWith('{')) return aliasVar(v.slice(1, -1));
  if (typeof v === 'string') return family(v);
  if (typeof v === 'number') return String(v);
  if (Array.isArray(v)) return v.map(family).join(', ');
  if (v?.colorSpace) {
    const [r, g, b] = v.components.map(c255);
    return v.alpha !== undefined ? `rgba(${r}, ${g}, ${b}, ${v.alpha})` : v.hex;
  }
  if (v?.unit) return px(v);
  return String(v);
}

/** The literal color a token resolves to, following aliases into the palette. */
function resolved(v) {
  if (typeof v === 'string' && v.startsWith('{')) {
    const key = v.slice(1, -1).split('.').slice(1).join('-');
    return resolved(prim.color[key].$value);
  }
  if (v?.colorSpace) {
    const [r, g, b] = v.components.map(c255);
    return v.alpha !== undefined ? `rgba(${r}, ${g}, ${b}, ${v.alpha})` : v.hex;
  }
  return val(v);
}

function* decls(group) {
  for (const [k, v] of Object.entries(group ?? {})) {
    if (k.startsWith('$')) continue;
    if (v && typeof v === 'object' && '$value' in v) yield [k, v];
  }
}

const pad = (rows) => {
  const w = Math.max(...rows.map(([n]) => n.length));
  return rows.map(([n, v]) => `${n.padEnd(w)} ${v};`);
};
const ind = (lines, n) => lines.map((l) => ' '.repeat(n) + l).join('\n');

// ── colors.css ──────────────────────────────────────────────────────────────

const paletteRows = [...decls(prim.color)].map(([k, t]) => [`--ol-${k}:`, val(t.$value)]);
const roleRows = (set) => [...decls(set.color)].map(([k, t]) => [`--${k}:`, val(t.$value)]);

const css = `/**
 * Olympia Brand — color tokens
 *
 * GENERATED by scripts/build-tokens.mjs from tokens/primitive.json and
 * tokens/semantic.{dark,light}.json. Do not hand-edit — change the JSON and
 * regenerate, or the two will drift.
 *
 * Dark is the default theme. Light is selected explicitly with
 * [data-theme="light"], or inherited from the OS preference when no theme has
 * been chosen.
 *
 * Every foreground token here clears WCAG 2.1 AA on the worst surface in its
 * theme — 4.5:1 for text (SC 1.4.3), 3:1 for non-text (SC 1.4.11). Verify with:
 *   node scripts/check-contrast.mjs
 */

:root {
  /* Palette — raw values. Prefer a role token below in any component. */
${ind(pad(paletteRows), 2)}

  /* Role tokens — dark, the default theme. */
${ind(pad(roleRows(dark)), 2)}
}

/* Light theme, explicitly selected. */
[data-theme="light"] {
${ind(pad(roleRows(light)), 2)}
}

/* Light theme from the OS preference, when none is explicitly set.
   :not([data-theme]) keeps an explicit choice winning over the OS.
   Must stay identical to the block above. */
@media (prefers-color-scheme: light) {
  :root:not([data-theme]) {
${ind(pad(roleRows(light)), 4)}
  }
}
`;

// ── colors.json ─────────────────────────────────────────────────────────────
// A flat, resolved view for consumers that cannot read CSS — a Qt/QML surface,
// a chart library taking literal values, an OG-card renderer. Every value is
// LITERAL here, never a var(), because a consumer of this file has no cascade.

const flat = (set) =>
  Object.fromEntries([...decls(set.color)].map(([k, t]) => [k, resolved(t.$value)]));

const colorsJson =
  JSON.stringify(
    {
      $comment:
        'GENERATED by scripts/build-tokens.mjs. Do not hand-edit. Values are fully resolved literals, not aliases, so a consumer with no CSS cascade can use them directly. Both themes are present: a token absent from one theme would silently inherit the other, which is a defect this file makes visible by construction.',
      palette: Object.fromEntries(
        [...decls(prim.color)].map(([k, t]) => [k, resolved(t.$value)]),
      ),
      dark: flat(dark),
      light: flat(light),
      font: Object.fromEntries(
        [...decls(prim.font)].map(([k, t]) => [k, [].concat(t.$value).join(', ')]),
      ),
      radius: Object.fromEntries([...decls(prim.radius)].map(([k, t]) => [k, px(t.$value)])),
    },
    null,
    2,
  ) + '\n';

// ── tailwind.css ────────────────────────────────────────────────────────────
// Registers the role tokens as Tailwind utilities so a consumer can write
// bg-bg-elevated, text-brand-green, border-border-strong. Re-exports colors.css
// through var(), so it holds no values of its own and needs no edit when a
// color changes. Nothing here compiles it — consuming repos do.

const themeRows = [
  ...[...decls(prim.color)].map(([k]) => [`--color-ol-${k}:`, `var(--ol-${k})`]),
  ...[...decls(dark.color)].map(([k]) => [`--color-${k}:`, `var(--${k})`]),
];
const fontRows = [...decls(prim.font)].map(([k, t]) => [
  `--font-${k}:`,
  [].concat(t.$value).map(family).join(', '),
]);
const radiusRows = [...decls(prim.radius)].map(([k, t]) => [`--radius-${k}:`, px(t.$value)]);

const tw = `/**
 * Olympia Brand — Tailwind CSS 4 @theme block
 *
 * GENERATED by scripts/build-tokens.mjs. Do not hand-edit.
 *
 * Import this from your globals.css after \`@import "tailwindcss"\`:
 *
 *   @import "tailwindcss";
 *   @import "olympia-brand/tokens/tailwind.css";
 *
 * Then the role tokens are available as utilities:
 *   <div class="bg-bg-elevated text-text-primary border-border-default">
 *   <span class="text-brand-green">
 *   <code class="font-mono">0xCfE1...</code>
 */

@import './colors.css';

@theme {
${ind(pad(themeRows), 2)}

${ind(pad(fontRows), 2)}

${ind(pad(radiusRows), 2)}
}

/* Focus is non-negotiable — SC 2.4.7. Every interactive element on every
   surface gets a visible keyboard indicator. Never remove this without
   replacing it with something at least as perceivable. */
:focus-visible {
  outline: 2px solid var(--focus-ring);
  outline-offset: 2px;
}

::selection {
  background: var(--brand-green-subtle);
  color: var(--text-primary);
}
`;

// ── write or check ──────────────────────────────────────────────────────────

const targets = [
  ['tokens/colors.css', css],
  ['tokens/colors.json', colorsJson],
  ['tokens/tailwind.css', tw],
];

if (process.argv.includes('--check')) {
  let stale = 0;
  for (const [rel, want] of targets) {
    let got = '';
    try {
      got = readFileSync(join(root, rel), 'utf8');
    } catch {
      got = '';
    }
    if (got === want) console.log(`  ok     ${rel}`);
    else {
      console.log(`  STALE  ${rel} — regenerate with: node scripts/build-tokens.mjs`);
      stale++;
    }
  }
  console.log(
    stale
      ? '\n  RESULT: token output is out of date with the JSON.'
      : '\n  RESULT: generated files match the JSON.',
  );
  process.exit(stale ? 1 : 0);
}

for (const [rel, out] of targets) {
  writeFileSync(join(root, rel), out);
  console.log('  wrote', rel);
}
